databases:
  - name: vgm-meridian-db
    plan: free
    databaseName: vgm_meridian

services:
  - type: web
    name: vgm-meridian
    runtime: python
    plan: free
    rootDir: .
    buildCommand: "bash build.sh"
    startCommand: "cd backend && gunicorn vgm_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: SECRET_KEY
        value: "76W$p$WwZBSDbDDPPFf+n-IdYJE90R2(kV8^P#PrKa2sAZBlyC"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: vgm-meridian-db
          property: connectionString
      - key: EMAIL_HOST_USER
        value: "vgmmeridiangroups@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: NODE_VERSION
        value: "20"
