databases:
  - name: vgm-meridian-db
    plan: free
    databaseName: vgm_meridian

services:
  - type: web
    name: vgm-meridian
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn vgm_backend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: vgm-meridian-db
          property: connectionString
      - key: EMAIL_HOST_USER
        value: "vgmmeridiangroups@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: NODE_VERSION
        value: "20"
